schema_version: 1

context:
  name: pydantic-xml
  version: "2.16.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pydantic_xml-${{ version }}.tar.gz
  sha256: 64ae5d8538a23706471f0b2007c9252ef290dff40c216dbc3051c79030aaf03f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.6.0,!=2.10.0b1
    - pydantic-core >=2.15.0
  run_constraints:
    - lxml >=4.9.0

tests:
  - python:
      imports:
        - pydantic_xml
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: pydantic xml extension
  license: Unlicense
  license_file: LICENSE
  homepage: https://github.com/dapper91/pydantic-xml

extra:
  recipe-maintainers:
    - synapticarbors
